### ISSUE TITLE
Question: partial correlation coefficient

### ISSUE THREAD

**Issue by susheelbhanu** [GraceYoon/SPRING#1]
Hey Grace, 
Thanks a lot for putting this together. I just wanted to clarify something regarding the `partial correlation coefficient`. I've used SpiecEasi in the past and obtained `weighted` adjacent matrices for my downstream graph construction. 

I'm sorry for the naive/dumb question, but is this the same as a weighted matrix?
```# Estimated partial correlation coefficient, same as negative precision matrix.
pcor.K <- as.matrix(SpiecEasi::symBeta(fit.spring$output$est$beta[[opt.K]], mode = 'maxabs'))
```

Also, I have an input matrix that has 84 samples and ~1500 ASVs, so is the faster version for the `SPRING` function available? Or is there a way to increase the number of cores or parallelise it some way?

Thank you,
Susheel

**Comment by GraceYoon** [comment]
I'm not quite sure how you obtained weighted adjacent matrices before. Did you use Meinshausen-Bühlmann's neighborhood selection for your graph? 

The faster version of SPRING will be updated soon! I'll let you know when it is available (hopefully within 2 weeks). Thank you!

**Comment by susheelbhanu** [comment]
Thanks for working on the faster update.

Meanwhile, this is how I got the weighted matrix - using the `glasso` method.

```
 se_first <- spiec.easi(first_Mtx, method='glasso', lambda.min.ratio=1e-2, nlambda=20, pulsar.params=list(rep.num=1000))
 
 se.cor  <- cov2cor(as.matrix(getOptCov(se_first)))
 weighted.adj.mat <- se.cor*getRefit(se_first)
 
 grph_first <- adj2igraph(weighted.adj.mat)
```

**Comment by GraceYoon** [comment]
Yes, you're right. For "mb" method, weighted adjacent matrices are constructed using beta values.
In the following link, weights on edges obtained by different methods are compared in histogram and codes are also available:
https://github.com/zdk123/SpiecEasi#analysis-of-american-gut-data
So sorry for the late reply!

**Comment by susheelbhanu** [comment]
Thanks a lot, Grace. So I could apply the SE method here to get the weights as well right?!

Also, just an FYI. A run that took me 7.5 hours with SpiecEasi on a HPC, is now running for 9 days with SPRING. Looking forward to having that `parallelized` version soon. 😄

**Comment by GraceYoon** [comment]
You can use SpiecEasi with "mb" or "glasso" method, but SPRING is currently working with "mb" method only. In any cases, you can get weights.
I'm sorry about the 9 days.. :( Unfortunately, the faster version is not a parallelized version, it's going to be faster because latent correlation calculation will be approximated very fast. For parallelization, you can increase "ncores" in SPRING function for now. Thanks!

**Comment by susheelbhanu** [comment]
Thanks, Grace. I did not realise there was an `ncores` function. Will try that out. Also, is the code for the `latent correlation calculation` updated yet? Could you please let me know when it is? 

Thanks again!

**Comment by GraceYoon** [comment]
FINALLY, the faster version of latent correlation calculation is available and implemented to SPRING. Thank you so much for your patience!!!
